### ISSUE TITLE
Config Parameter to Link to raw image

### ISSUE THREAD

**Issue by ebouchut** [neenjaw/compile-mermaid-markdown-action#31]
Hi @neenjaw,

I find your Github Action very useful and I'm using it in our [project](https://github.com/bet-no-loss/bet-no-loss). 
Thank you.

I convert mermaid diagrams to SVG and it would be great to have a configuration parameter to choose the **[raw URL](https://raw.githubusercontent.com/bet-no-loss/bet-no-loss/master/doc/img/README-md-1.svg)** instead of the [regular URL](https://github.com/bet-no-loss/bet-no-loss/blob/master/doc/img/README-md-1.svg) in the generated/inserted Markdown diagram URL.

I'm asking this because Github only displays part of the SVG image in what I call the regular Github image URL whereas of course the whole SVG image with the raw image URL. 

Yes I know it's just one click away, but readers not used to using Github may not know they can use the `Raw` button to view it full size.

**Comment by neenjaw** [comment]
Thanks for your interest in this action!! 💙 🎉 

I like the idea, but I vaguely remember encountering some difficulty doing something like this when I was creating this action (which was a while ago now).  I think it is doable, but it will need quite a bit of work, since it will need to determine the branch that the commit/pr is being made to so that the absolute URL can be generated and written into the markdown file.

Currently, only a relative (or absolute from the root of the repository) path is written into the file, and github generates the full image source URL.

I'm not sure of a quick way to do this, and I don't really have the time to undertake this feature.  If you are interested in contributing, I am open to reviewing PRs.  My standard is that PRs generally must maintain the current happy-path for users of the action, so this (like you said) would be an optional configuration.
